logging:
  level: debug

elasticjob:
  serverlists: localhost:2181
  namespace: boot-job

spring:
  datasource:
    url: jdbc:mysql://119.23.232.89:3307/test?useUnicode=true&characterEncoding=utf-8&verifyServerCertificate=false&useSSL=false&requireSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
#  自动创建更新验证数据库结构
  jpa:
    hibernate:
      ddl-auto: create-drop
