server:
  port: 8081
  servlet:
    path: /boot

prop:
  upload-folder: files/

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

logging:
  level:
    org.boot.uploader.*: debug

