server:
  port: 8081

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.boot.security: DEBUG

spring:
  thymeleaf:
    cache: false

jwt:
  secret: sign